export const API_GET_GROUP='API_GET_GROUP';
export const API_SET_GROUP='API_SET_GROUP';
export const API_CREATE_GROUP='API_CREATE_GROUP';
export const API_CREATE_GROUP_MEMBERSHIP='API_CREATE_GROUP_MEMBERSHIP';
