export const API_CREATE_FEE_HEAD='API_CREATE_FEE_HEAD';
export const API_SET_FEE_HEAD='API_SET_FEE_HEAD';
export const API_GET_FEE_HEAD='API_GET_FEE_HEAD';
export const API_DELETE_FEE_HEAD='API_DELETE_FEE_HEAD';