export const API_GET_SUBJECT='API_GET_SUBJECT';
export const API_SET_SUBJECT='API_SET_SUBJECT';
export const API_DELETE_SUBJECT='API_DELETE_SUBJECT';
export const API_CREATE_SUBJECT='API_CREATE_SUBJECT';