export const API_LEVEL_CLASSES = 'REQUEST_CLASSES';
export const API_LEVEL_FEES = 'REQUEST_FEES';
export const API_LEVEL_SUBJECTS = 'REQUEST_SUBJECTS';
export const API_LEVEL_GET = 'REQUEST_LEVEL_GET';
export const ADD_TO_DELETESTACK='ADD_TO_DELETESTACK';
export const API_LEVEL_CREATE='API_CREATE_LEVEL';
export const API_LEVEL_DELETE='API_DELETE_LEVEL';


export const API_LEVEL_SAVE='SAVE_LEVEL';
export const PREPARE_CREATE_LEVEL='PREPARE_CREATE_LEVEL';
export const API_LEVELS_POST='DELETE_LEVELS';


export const RESTAPI_RECEIVE='RECEIVE';
export const RESTAPI_REQUEST='REQUEST';
