export const API_LIST_STUDYCLASS = 'API_CLASSES';
export const API_GET_STUDYCLASS = 'API_CLASSE_INFO';
export const API_SAVE_STUDYCLASS = 'API_SAVE_CLASSE_INFO';
export const API_CREATE_STUDYCLASS = 'API_CREATE_CLASS_INFO';
export const API_DELETE_STUDYCLASS = 'API_DELETE_STUDYCLASS';
export const API_CLASS_AGGREGATE='API_CLASS_AGGREGATE';
